# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6aae2db399b02b2991ed208a210ede9ad5d888d47d6dffe99059867fd4f6b8d6b886321afc938d89ce93e8319df9ec609c1049af9d8178e9e9e60987cd0a5565

test:
  secret_key_base: 8e0b72eac7fc9a47c3a8399c1f3fd73ba82ce5d5576680b304ac3285571e79c58557e322097d6791f871262b0e10d4a07d622ed3e705974f56fc864ac639b213

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
